### ISSUE TITLE
places block when opening chest

### ISSUE THREAD

**Issue by Raezar** [RTRGitHub/RTRRedux#536]
when you have a block in your hand and open the chest it places the block

**Comment by Solidflip** [comment]
I cant reproduce this on my side at all. I think it must be client side. But to try to help, provide logs. Console log/client log etc.

**Comment by dragonaslin** [comment]
i can and it was fixed when flip took out mcmmo it was a hand thing

**Comment by frogger35** [comment]
issue still persists. I've tried clicking hoppers, drums, and actually additions machines. A block is still being placed when rightclicking to open the inventoriums.
